### ISSUE TITLE
android.keystore 文件丢失？

### ISSUE THREAD

**Issue by tmxd09887** [keep2iron/Fast4Android#1]
Error:(9, 0) Cannot convert URL 'D:/keystore/android.keystore' to a file.
<a href="openFile:C:\Users\winner\.AndroidStudio2.3\project\Fast4Android-master\lib-fast4Android-core\build.gradle">Open File</a>

**Comment by keep2iron** [comment]
不好意思，这里的上传的时候没有注意。这个地方的可以自己定义一下的
